- examples/sentence_similarity/gensen_aml_deep_dive.ipynb
- tools/generate_conda_file.py
added notebooks, contrib to conda env to address #379 
small updates to installing and folder names used in gensen on aml notebook
> Updated conda to install notebooks/contrib and minor gensen aml update

- cgmanifest.json
Going forward, this file will replace manual registrations of third party components that we use in our repo.
> Add cgmanifest.json with third party repo info.

- README.md
> related repos links

- utils_nlp/dataset/url_utils.py
if work directory doesn't exist, this function will fail
> Create work directory

- tools/generate_conda_file.py
changed contribs to contrib
https://github.com/microsoft/nlp/issues/387
> changed contribs to contrib

- tests/ci/component_governance.yml
- tests/ci/cpu_unit_tests_linux.yml
- tests/ci/gpu_unit_tests_linux.yml
- tests/ci/notebooks_cpu_unit_tests_linux.yml
- tests/ci/notebooks_gpu_unit_tests_linux.yml
- tools/generate_requirements_txt.py
Added automatic component governance 
the build passed, Hong please take a look: https://dev.azure.com/best-practices/nlp/_build/results?buildId=8411
> component governance

- README.md
Added focus areas of the repository
Adds focus areas to the repository and stresses the importance of non english languages. 
Adds supported languages to the existing table.
> Added focus areas for the repository

- utils_nlp/README.md
Fixes documentation url / description.
- [ x ] My code follows the code style of this project, as detailed in our [contribution guidelines](../CONTRIBUTING.md).
- [ x ] I have updated the documentation accordingly.
> Fix model interpretation utilities documentation 

- examples/text_classification/tc_dac_bert_ar.ipynb
- tests/conftest.py
- tests/integration/test_notebooks_text_classification.py
- utils_nlp/dataset/dac.py
> add ar example

- examples/text_classification/tc_mnli_bert.ipynb
> remove unused import

- tests/integration/test_notebooks_text_classification.py
reduce batch size in test
#407
> reduce batch size in tc ar notebook's test

- examples/README.md
- examples/entailment/entailment_xnli_bert_azureml.ipynb
- examples/question_answering/bidaf_aml_deep_dive.ipynb
- examples/question_answering/pretrained-BERT-SQuAD-deep-dive-aml.ipynb
- examples/question_answering/question_answering_system_bidaf_quickstart.ipynb
- examples/sentence_similarity/automl_local_deployment_aci.ipynb
- examples/sentence_similarity/automl_with_pipelines_deployment_aks.ipynb
- examples/sentence_similarity/bert_senteval.ipynb
- examples/sentence_similarity/gensen_aml_deep_dive.ipynb
- examples/text_classification/tc_bert_azureml.ipynb
Added pixelserver and disclaimer to examples readme and azureml notebooks
> Pixelserver

- utils_nlp/dataset/multinli.py
Code used to download and extract data is more modularized and reusable
> refactor: remove replication of code

- utils_nlp/models/transformers/sequence_classification.py
Created a `SupportedModels` class 
This is needed for the following:
1. More Pythonic OOP implementation
1. Above code rewrite
1. One point to refactor for all PyTorch Transformer classes the package supports
> Refactor to generalize supported models

- utils_nlp/models/transformers/common.py
Generalized get device code so that it can be used in different places.
> Generalize get device code.

- utils_nlp/models/transformers/common.py
- utils_nlp/models/transformers/sequence_classification.py
added predict function
updated transformer import
other edits
> Tc transformers

- utils_nlp/models/transformers/named_entity_recognition.py
Add TokenClassification class and class TokenClassificationProcessor class for named entity recognition. So far, only pretrained BERT model is supported.
> Add token classifiction for named entity recognition.

- utils_nlp/dataset/pytorch.py
> Bug fix in QADataset.

- examples/README.md
Remove mention of embedding and stick to just models
Simplifying entry for Sentence similarity. Also mentioning language for every scenario #benderrule
> Simplify Sentence similarity entry

- setup.py
- utils_nlp/models/xlnet/sequence_classification.py
Adding Microsoft license header
> Add license headers

- tools/generate_conda_file.py
@roalexan @yueguoguo and I are having so much fun with the tests in Recommenders. We discovered that having papermill in pip instead of conda causes problems. This PR will prevent problems in the future
> Move papermill from pip to conda

- examples/README.md
> Add newly supported methods to examples table.

- README.md
Make models for sentence similarity consistent with other scenarios.
Make models for sentence similarity consistent with other scenarios.
> Simplify models for sentence similarity

- examples/README.md
- tools/README.md
- tools/remove_pixelserver.py
Added script to remove pixelserver tracking.
> Added script to remove pixelserver tracking

- utils_nlp/models/transformers/common.py
This basically allows us to input a customer optimizer or scheduler without any other change in the code. The only problem I see here is that this situation can happen, I create an optimizer with lr=0.2 and then in fit I have lr=0.5, then change will take 0.2, because the lr goes with the optimizer, not with fit
> optimizer and scheduler out

- tests/unit/test_common_pytorch_utils.py
- utils_nlp/common/pytorch_utils.py
- utils_nlp/models/bert/sequence_classification.py
- utils_nlp/models/bert/sequence_classification_distributed.py
- utils_nlp/models/bert/sequence_encoding.py
- utils_nlp/models/bert/token_classification.py
- utils_nlp/models/transformers/common.py
- utils_nlp/models/xlnet/sequence_classification.py
> refactored get_device

- examples/entailment/README.md
> Adding language #bender rule

- examples/model_explainability/README.md
> Adding language #benderrule

- NOTICE.txt
- README.md
- examples/question_answering/pretrained-BERT-SQuAD-deep-dive-aml.ipynb
- examples/text_classification/tc_mnli_xlnet.ipynb
- tests/integration/test_notebooks_question_answering.py
- tools/generate_conda_file.py
- utils_nlp/models/bert/README.md
- utils_nlp/models/bert/common.py
- utils_nlp/models/bert/token_classification.py
- utils_nlp/models/xlnet/README.md
- utils_nlp/models/xlnet/common.py
- utils_nlp/models/xlnet/sequence_classification.py
> Remove pytorch-transformers from dependencies.

- tests/unit/test_notebooks_cpu.py
- tests/unit/test_notebooks_gpu.py
https://github.com/microsoft/nlp-recipes/issues/480
> Changed temp to temporary files

- examples/entailment/entailment_xnli_bert_azureml.ipynb
fix import error and max_nodes for the cluster, the errors that I encountered during running the notebook
https://github.com/microsoft/nlp-recipes/issues/496
> fix notebook entailment_xnli_bert_azureml

- utils_nlp/__init__.py
Bump version release number to v2
Creating a new major release with transformer work.
> update nlp recipes feature release number to v2

- README.md
- utils_nlp/models/transformers/question_answering.py
- utils_nlp/models/transformers/sequence_classification.py
- updated Readme
- add docstrings to sequence_classification
> docstrings and readme edits

- examples/embeddings/README.md
> Fix display issues in table

- utils_nlp/models/transformers/common.py
- utils_nlp/models/transformers/question_answering.py
fix num_gpus issue when DataParallel is used
> fix num_gpus issue

- tools/generate_conda_file.py
There was a security risk with tensorflow 1.12.0 according to the CG detection results.
> Upgrade tensorflow to 1.15.0

- utils_nlp/models/transformers/sequence_classification.py
> docstring edits

- tools/generate_conda_file.py
> Remove unnecessary dependencies

- utils_nlp/models/transformers/named_entity_recognition.py
add support for distilbert for NER
> add support for distilbert

- README.md
- examples/README.md
- tools/generate_conda_file.py
Upgrade tensorflow to 1.15 for transformers support.
> update tensorflow and cudatoolkit

- examples/entailment/entailment_multinli_transformers.ipynb
Updated entailment example to match recent release updates.
> update entailment example

- README.md
Add DialoGPT link to References section
> Add DialoGPT reference

- .flake8
- pyproject.toml
reverting back to black's max line length of 88
> update line len

- pyproject.toml
- tests/unit/test_common_pytorch_utils.py
- tests/unit/test_extractive_summarization.py
- tests/unit/test_transformers_sequence_classification.py
- utils_nlp/common/pytorch_utils.py
- utils_nlp/models/bert/sequence_classification.py
- utils_nlp/models/bert/sequence_classification_distributed.py
- utils_nlp/models/bert/sequence_encoding.py
- utils_nlp/models/transformers/common.py
- utils_nlp/models/transformers/extractive_summarization.py
- utils_nlp/models/transformers/named_entity_recognition.py
- utils_nlp/models/transformers/question_answering.py
- utils_nlp/models/transformers/sequence_classification.py
Add a function for model and optimizer preparation so that things are done in the correct order.
Initial commit of changes to common files. 
Child classes need to be updated to leverage this function.
> [WIP] Common model and optimizer changes

- tests/unit/test_transformers_token_classification.py
- utils_nlp/models/transformers/named_entity_recognition.py
> fix new preds function

- utils_nlp/dataset/dac.py
> update dataset url

- tools/generate_conda_file.py
> Set cudatoolkit to 10.1

- examples/text_summarization/abstractive_summarization_unilm_cnndm.ipynb
- tests/integration/test_notebooks_unilm_abstractive_summarization.py
- tools/generate_conda_file.py
> Hlu/add s2s ft to generate conda file.py

- tools/generate_conda_file.py
> Replace s2sft commit hash with release tag.

- README.md
> add blog links

- README.md
- examples/text_summarization/abstractive_summarization_minilm_cnndm.ipynb
- tests/ci/gpu_unit_tests_linux.yml
- tests/conftest.py
- tests/integration/test_notebooks_minilm_abstractive_summarization.py
- tests/unit/test_abstractive_summarization_seq2seq.py
- utils_nlp/models/transformers/abstractive_summarization_seq2seq.py
Changed the unilm utilities to support  MiniLM for abstractive summarization
Added a notebook to show how to use MiniLM
Added unit test and integration test
Minor changes on the dataset utilities to support shortening dataset
> Daden/minilm Add MiniLM for Abstractive Summarization

- utils_nlp/dataset/wikigold.py
- utils_nlp/models/transformers/abstractive_summarization_seq2seq.py
- utils_nlp/models/transformers/common.py
> Bleik/add models - minor edits

- utils_nlp/dataset/multinli.py
Leverage NYU Jiant Toolkit preprocessed tsv data source, avoiding the need to preprocess.
> Feat: add functionality to download MNLI preprocessed tsv data.

- SETUP.md
Updating notebook vm link
Updating notebook vm link
Pointing to new AzureML compute instance
> Updating notebook vm link

- README.md
Adding additional models for text classification. 
Also adding languages based on the list of currently supported models
['albert-base-v1',
'albert-base-v2',
'albert-large-v1',
'albert-large-v2',
'albert-xlarge-v1',
'albert-xlarge-v2',
'albert-xxlarge-v1',
'albert-xxlarge-v2',
'bart-large',
'bart-large-cnn',
'bart-large-mnli',
'bart-large-xsum',
'bert-base-cased',
'bert-base-cased-finetuned-mrpc',
'bert-base-chinese',
'bert-base-dutch-cased',
'bert-base-finnish-cased-v1',
'bert-base-finnish-uncased-v1',
'bert-base-german-cased',
'bert-base-german-dbmdz-cased',
'bert-base-german-dbmdz-uncased',
'bert-base-japanese',
'bert-base-japanese-char',
'bert-base-japanese-char-whole-word-masking',
'bert-base-japanese-whole-word-masking',
'bert-base-multilingual-cased', …
> Adding additional models to text classification

- README.md
Update link for MT-DNN
Updating link to MTDNN
Link for MT-DNN is obsolete
> Update link for MT-DNN

- utils_nlp/dataset/xnli.py
> update xnli links

- examples/named_entity_recognition/ner_wikigold_transformer.ipynb
- utils_nlp/dataset/ner_utils.py
- utils_nlp/dataset/wikigold.py
Currently, NER notebook doesn't use the packaged wikigold dataset available from the utilities library
Simplifies the notebook by abstracting the dataset
> Changes NER notebook to use the dataset utilities

- .gitignore
- examples/text_classification/tc_mnli_mtdnn.ipynb
1. This PR adds a text classification notebook with MT-DNN on MNLI dataset
1. It leverages the pip installable package from MT-DNN repo, using the components defined in that repo
This is required to add a new model to the NLP Recipes - MTDNN
> MTDNN Text classification notebook on MNLI dataset
